### ISSUE TITLE
Support other OSes too

### ISSUE THREAD

**Issue by Arabus** [saltstack-formulas/docker-formula#26]
As an avid gentoo user I feel kinda left out by the initial formula. I know that supporting every flavor of OS is kinda hard, but a little flexibility to at least fail gracefully when not dealing with debian.

A small note in the README that currently only debian and ubuntu are supported might suffice for the time being.

I will look into finding a way to integrate gentoo into the existing code but I expect it to be a little more than just one pull request.

**Comment by gravyboat** [comment]
This is definitely a problem that many formulas have since they're mostly just community contributions. I'm not aware of anyone who contributes currently that is using Gentoo unfortunately. If you end up making changes (probably quite a few in the map.jinja from what I am seeing), please open a PR so we can get some of that functionality in!

**Comment by techhat** [comment]
I would love to see a document or template that discusses supporting Gentoo at large in the formula repos. Also, you know, the other distros.

**Comment by Arabus** [comment]
I had a few looks at the salt-formula and the openssh formula and both of them seem to have figured out a way to structure these kind of variables in a convenient way.

As a first move I'd suggest moving all kinds of default variable values to a separate file, e.g. default.yaml  and then merging those values with the os and distro dependent ones inside the map.jinja. 

If properly implemented these values then live inside their own subnamespace of pillar, e.g. pillar.default_settings.docker or something like that. That way the state files can reference them without fear of clashing with other pillar information.

After this has been done, it should be possible to create the correct blocks of installation and configuration depending on the linux distro and release.

I am currently trying to extract current map,jinja variables to a default.yaml but seem to run into a problem with the set kernel part when running on a non debian system because of the missing grains:

#default.yaml
```yaml
docker:
  registry:
    description: 'Docker Registry'
    port: 5000
    restart: False
    search_backend: sqlalchemy
    amazon:
      storage_path: /registry
      settings_flavor: s3
  kernel:
    pkg:
      name: linux-image-amd64
      fromrepo: wheezy-backports
    pkgrepo:
      name: 'deb http://http.debian.net/debian wheezy-backports main'
      humanname: 'Wheezy Backports'
      dist: 'wheezy-backports'
  compose:
    version: 1.1.0
  pkg:
    version: 1.6.2
```
#map.jinja
```jinja
{% import_yaml "docker/defaults.yaml" as default_settings %}

{% set kernel = salt['grains.filter_by']({
    'wheezy': {
        'pkg': {
            'name': 'linux-image-amd64',
            'fromrepo': 'wheezy-backports',
        },
        'pkgrepo': {
            'name': 'deb http://http.debian.net/debian wheezy-backports main',
            'humanname': 'Wheezy Backports',
            'dist': 'wheezy-backports',
        },
    },
    'precise': {
        'pkg': {
            'pkgs': ['linux-image-generic-lts-raring', 'linux-headers-generic-lts-raring'],
        },
    },
},grain='lsb_distrib_codename', merge=salt['pillar.get']('docker:lookup:kernel'), default='wheezy') %}

{% set pkg = salt['pillar.get']('docker-pkg:lookup', { 'version': 1.6.2 } ) %}

{% do default_settings.docker.kernel.update(kernel) %}
{% do default_settings.docker.pkg.update(pkg) %}

{% set docker_settings = salt['pillar.get']('docker', default=default_settings.docker, merge=True) %}
```

```bash salt-call --local state.show_sls docker```
results in an error message:

```
[CRITICAL] Rendering SLS 'base:docker' failed: Jinja variable 'dict object' has no attribute 'lsb_distrib_codename'
local:
    - Rendering SLS 'base:docker' failed: Jinja variable 'dict object' has no attribute 'lsb_distrib_codename'
```

**Comment by iggy** [comment]
try
s/lsb_distrib_codename/oscodename/

**Comment by ozialien** [comment]
Yeah I think in order to be a framework it has to at least support more than one os flavor.

**Comment by gravyboat** [comment]
@ozialien We're happy to merge in PRs that add this support!

**Comment by blbradley** [comment]
Support for RedHat based OS's was introduced in #107.

@Arabus If you were still intended on implementing support for Gentoo, please let us know. Otherwise, I'll close this after about 30 days.

**Comment by Arabus** [comment]
Though I'd really like to habe this, I currently have no time at my hands to give you a proper pull request. I am very sorry for keeping you, please close this ticket.

**Comment by blbradley** [comment]
No problem! Feel free to open a new issue regarding this in the future.
