### ISSUE TITLE
Pip can fail and it's blocking

### ISSUE THREAD

**Issue by toopy** [saltstack-formulas/docker-formula#53]
Here is what I get with the `pip-formula`, it should be better not to handle it here and let the user choose between pip formula or the working way for him. I'm block with this issue and I will need to extend `docker-py requirements` state to not depend from the python-pip package of jessie.

Here is what I get now:

```
root@ci-slave:/# apt-cache policy python-pip
python-pip:
  Installed: 1.5.6-5
  Candidate: 1.5.6-5
  Version table:
 *** 1.5.6-5 0
        500 http://ftp.fr.debian.org/debian/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status
root@ci-slave:/# apt-cache policy python-requests
python-requests:
  Installed: 2.4.3-6
  Candidate: 2.4.3-6
  Version table:
 *** 2.4.3-6 0
        500 http://ftp.fr.debian.org/debian/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status
root@ci-slave:/# pip version
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
root@ci-slave:/#
```

then:

```
----------
          ID: docker-py requirements
    Function: pip.installed
        Name: docker-py
      Result: None
     Comment: Error installing 'docker-py': Traceback (most recent call last):
                File "/usr/bin/pip2", line 9, in <module>
                  load_entry_point('pip==1.5.6', 'console_scripts', 'pip2')()
                File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
                  return get_distribution(dist).load_entry_point(group, name)
                File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
                  return ep.load()
                File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
                  ['__name__'])
                File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
                  from pip.vcs import git, mercurial, subversion, bazaar  # noqa
                File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
                  from pip.download import path_to_url
                File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
                  from requests.compat import IncompleteRead
              ImportError: cannot import name IncompleteRead
     Started: 19:17:04.062652
    Duration: 117.275 ms
     Changes:   
----------
```

**Comment by toopy** [comment]
cf.: https://github.com/saltstack-formulas/docker-formula/pull/50

**Comment by toopy** [comment]
```
root@ci-slave:~# pip --version
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)
```
It can't work with `requests==2.5.3`: https://github.com/docker/docker-py/blob/master/requirements.txt#L1

We should update pip itself at the install of docker-py.

**Comment by blbradley** [comment]
I think this was closed in #54. Feel free to reopen if it wasn't.
